#!/usr/bin/env python
"""Generate figures/heights.css from the exported HTML figures.

    python figures/write_heights_css.py

Each Plotly export already carries the height the notebook gave it via
`style(pf, height=...)`. Reading it back means the site never guesses: no aspect
ratios to maintain, no per-figure markup, and no scrollbars, because the frame
is exactly as tall as the figure asked to be.

The .qmd names the figure and nothing else:

    <div class="fig-frame" data-fig="dist_daily_stations">
      <iframe src="../figures/html/dist_daily_stations.html"></iframe>
    </div>

Re-run this after re-exporting; it updates every page at once.
"""
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
HTML = HERE / "html"

# The modebar sits above the plot area and is not counted in the layout height.
CHROME_PX = 16

def declared_height(path):
    """The `height` Plotly wrote into the figure's layout, in pixels."""
    text = path.read_text(errors="ignore")
    # The layout JSON is embedded in the Plotly.newPlot call. Take the height
    # that appears inside a "layout" object rather than any height in the data,
    # which is why this looks for the key in context rather than anywhere.
    m = re.search(r'"layout"\s*:\s*\{.*?"height"\s*:\s*(\d+(?:\.\d+)?)',
                  text, re.S)
    if m:
        return float(m.group(1))
    # Fall back to any height at all, then to a sane default -- a figure with no
    # declared height is responsive in both directions and 450 matches the
    # notebook's `style()` default.
    m = re.search(r'"height"\s*:\s*(\d+(?:\.\d+)?)', text)
    return float(m.group(1)) if m else 450.0

if not HTML.is_dir():
    sys.exit(f"{HTML} not found -- export the interactive figures first")

heights = {p.stem: declared_height(p) for p in sorted(HTML.glob("*.html"))}
if not heights:
    sys.exit(f"no .html figures in {HTML}")

lines = [
    "/* GENERATED by figures/write_heights_css.py -- do not edit by hand.",
    " *",
    " * One rule per figure, keyed on `data-fig`. The height is the one the",
    " * notebook set with `style(pf, height=...)`, read back from the export, so",
    " * the figure and its frame cannot disagree and nothing needs maintaining",
    " * in two places.",
    " */",
    "",
]
for stem, h in sorted(heights.items()):
    lines.append(f'.fig-frame[data-fig="{stem}"] {{ height: '
                 f'{int(h) + CHROME_PX}px; }}')
lines.append("")

(HERE / "heights.css").write_text("\n".join(lines))
(HERE / "heights.json").write_text(json.dumps(
    {k: int(v) for k, v in sorted(heights.items())}, indent=1))
print(f"figures/heights.css: {len(heights)} figures "
      f"({min(heights.values()):.0f}-{max(heights.values()):.0f}px "
      f"+ {CHROME_PX}px chrome)")
